"""Initial migration

Revision ID: cd5e9c916c4b
Revises: 
Create Date: 2020-12-03 17:38:52.392780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd5e9c916c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'ApplicationDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('application', 'ApplicationStatus',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('application', 'PositionTitle',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('application', 'UserId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('applicationlocation', 'CityId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('applicationlocation', 'StateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('city', 'CityName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('company', 'CompanyName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('recruiter', 'CompanyId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('recruiter', 'RecFirstName',
               existing_type=mysql.CHAR(length=255),
               nullable=False)
    op.alter_column('recruiter', 'RecLastName',
               existing_type=mysql.CHAR(length=255),
               nullable=False)
    op.add_column('state', sa.Column('StateAbbr', sa.String(length=2), nullable=False))
    op.alter_column('state', 'StateName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'Email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'FirstName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'LastName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['Email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'LastName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'FirstName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'Email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('state', 'StateName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('state', 'StateAbbr')
    op.alter_column('recruiter', 'RecLastName',
               existing_type=mysql.CHAR(length=255),
               nullable=True)
    op.alter_column('recruiter', 'RecFirstName',
               existing_type=mysql.CHAR(length=255),
               nullable=True)
    op.alter_column('recruiter', 'CompanyId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('company', 'CompanyName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('city', 'CityName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('applicationlocation', 'StateId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('applicationlocation', 'CityId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('application', 'UserId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('application', 'PositionTitle',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('application', 'ApplicationStatus',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('application', 'ApplicationDate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
